export enum Types {
    SET_USER_DATA = "SET_USER_DATA",
    UPDATE_USER_RECENT_TRANSACTIONS = "UPDATE_USER_RECENT_TRANSACTIONS",
    ADD_TRANSACTION =  "ADD_TRANSACTION",
    ADD_LOAN = "ADD_LOAN" ,
    UPDATE_ACCOUNT_BALANCE = "UPDATE_ACCOUNT_BALANCE"
}
  
  